// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpperToolsProject.Data;

namespace UpperToolsProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210915121213_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("UpperToolsProject.Models.Atividade", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("EmpresaCnpj")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("EmpresaCnpj1")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("EmpresaCnpj");

                    b.HasIndex("EmpresaCnpj1");

                    b.ToTable("Atividade");
                });

            modelBuilder.Entity("UpperToolsProject.Models.Empresa", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Abertura")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("DataSituacao")
                        .HasColumnType("text");

                    b.Property<string>("DataSituacaoEspecial")
                        .HasColumnType("text");

                    b.Property<string>("Efr")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fantasia")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<string>("MotivoSituacao")
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Porte")
                        .HasColumnType("text");

                    b.Property<string>("Situacao")
                        .HasColumnType("text");

                    b.Property<string>("SituacaoEspecial")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.Property<string>("UltimaAtualizacao")
                        .HasColumnType("text");

                    b.HasKey("Cnpj");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("UpperToolsProject.Models.Qsa", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("EmpresaCnpj")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Qual")
                        .HasColumnType("text");

                    b.HasKey("Nome");

                    b.HasIndex("EmpresaCnpj");

                    b.ToTable("Qsa");
                });

            modelBuilder.Entity("UpperToolsProject.Models.Atividade", b =>
                {
                    b.HasOne("UpperToolsProject.Models.Empresa", null)
                        .WithMany("AtividadePrincipal")
                        .HasForeignKey("EmpresaCnpj");

                    b.HasOne("UpperToolsProject.Models.Empresa", null)
                        .WithMany("AtividadesSecundarias")
                        .HasForeignKey("EmpresaCnpj1");
                });

            modelBuilder.Entity("UpperToolsProject.Models.Qsa", b =>
                {
                    b.HasOne("UpperToolsProject.Models.Empresa", null)
                        .WithMany("Qsa")
                        .HasForeignKey("EmpresaCnpj");
                });

            modelBuilder.Entity("UpperToolsProject.Models.Empresa", b =>
                {
                    b.Navigation("AtividadePrincipal");

                    b.Navigation("AtividadesSecundarias");

                    b.Navigation("Qsa");
                });
#pragma warning restore 612, 618
        }
    }
}
